const {
  SPOTIFYWRAP_DB_USER = "",
  SPOTIFYWRAP_DB_PASSWORD = "",
  SPOTIFYWRAP_DB_URI = "",
  SPOTIFYWRAP_DB_NAME = "",
  SPOTIFYWRAP_DB_COLLECTION = "",
  SPOTIFYWRAP_API_BASE_URL = "",
  SPOTIFYWRAP_API_USER = "",
  SPOTIFYWRAP_API_PASSWORD = "",
} = process.env;

module.exports = {
  SPOTIFYWRAP_DB_USER,
  SPOTIFYWRAP_DB_PASSWORD,
  SPOTIFYWRAP_DB_URI,
  SPOTIFYWRAP_DB_NAME,
  SPOTIFYWRAP_DB_COLLECTION,
  SPOTIFYWRAP_API_BASE_URL,
  SPOTIFYWRAP_API_USER,
  SPOTIFYWRAP_API_PASSWORD,
};
